version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: warehouse-sql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: WarehouseApi/Dockerfile
    container_name: warehouse-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  sql_data:
